(function initializeProductCatalog() {
const products = [
  {
    id: 1,
    name: "Ndakava Dog",
    category: "Ndakava",
    description: "A satisfying Kenyan quick bite with bold FBI Bites flavour.",
    price: 150,
    image: "images/Ndakava dog.jpg",
    featured: true,
    available: true,
  },
  {
    id: 2,
    name: "FBI Fries",
    category: "Fries",
    description: "Crispy, golden and dangerously easy to finish in one sitting.",
    price: 100,
    image: "images/Fries.jpg",
    featured: false,
    available: true,
  },
  {
    id: 3,
    name: "Eggballs",
    category: "Snacks",
    description: "A small snack with big craving energy and budget-friendly value.",
    price: 50,
    image: "images/Eggballs.jpg",
    featured: false,
    available: true,
  },
  {
    id: 4,
    name: "Smocha",
    category: "Quick Bites",
    description: "A Kenyan favourite for quick hunger, quick bites and quick wins.",
    price: 100,
    image: "images/Smocha.jpg",
    featured: false,
    available: true,
  },
  {
    id: 5,
    name: "Meatchapo",
    category: "Chapati Meals",
    description: "Chapati filled or served with minced meat for a filling, affordable quick meal.",
    price: 70,
    image: "images/meatchapo.jpg",
    featured: true,
    available: true,
  },
  {
    id: 6,
    name: "Ndakava Pork",
    category: "Ndakava",
    description: "A pork version of the FBI Bites Ndakava experience.",
    price: 130,
    image: "images/ndakava-pork.jpg",
    featured: false,
    available: true,
  },
  {
    id: 7,
    name: "Chicken Wings",
    category: "Chicken",
    description: "FBI Bites chicken wings.",
    price: 100,
    priceIsEstimate: true,
    image: "images/chicken-wings.jpg",
    featured: false,
    available: true,
  },
  {
    id: 8,
    name: "Chicken Thigh",
    category: "Chicken",
    description: "A chicken thigh prepared FBI Bites style.",
    price: 180,
    priceIsEstimate: true,
    image: "images/chicken-thigh.jpg",
    featured: false,
    available: true,
  },
  {
    id: 9,
    name: "Chicken Drumstick",
    category: "Chicken",
    description: "A chicken drumstick prepared FBI Bites style.",
    price: 130,
    priceIsEstimate: true,
    image: "images/chicken-drumstick.jpg",
    featured: false,
    available: true,
  },
  {
    id: 10,
    name: "Chicken Breast",
    category: "Chicken",
    description: "Chicken breast prepared FBI Bites style.",
    price: 220,
    priceIsEstimate: true,
    image: "images/chicken-breast.jpg",
    featured: false,
    available: true,
  },
  {
    id: 11,
    name: "Chicken Leg",
    category: "Chicken",
    description: "A chicken leg prepared FBI Bites style.",
    price: 250,
    priceIsEstimate: true,
    image: "images/chicken-leg.jpg",
    featured: false,
    available: true,
  },
  {
    id: 12,
    name: "Chicken Pieces",
    category: "Chicken",
    description: "Chicken pieces prepared FBI Bites style.",
    price: 150,
    priceIsEstimate: true,
    image: "images/chicken-pieces.jpg",
    featured: false,
    available: true,
  },
  {
    id: 13,
    name: "Rabbit Meat",
    category: "Meat",
    description: "Tender rabbit meat prepared as an FBI Bites meat option.",
    price: 350,
    priceIsEstimate: true,
    image: "images/rabbit-meat.jpg",
    featured: false,
    available: true,
  },
  {
    id: 14,
    name: "Boiled Egg",
    category: "Snacks",
    description: "Simple boiled eggs for a quick and affordable bite.",
    price: 30,
    priceIsEstimate: true,
    image: "images/boiled-egg.jpg",
    featured: false,
    available: true,
  },
  {
    id: 15,
    name: "Minced Meat",
    category: "Meat",
    description: "Minced meat prepared FBI Bites style.",
    price: 120,
    priceIsEstimate: true,
    image: "images/minced-meat.jpg",
    featured: false,
    available: true,
  },
  {
    id: 16,
    name: "Coca-Cola 300ml",
    category: "Drinks",
    description: "Chilled Coca-Cola soft drink, 300ml.",
    price: 70,
    priceIsEstimate: true,
    image: "images/coca-cola-300ml.jpg",
    featured: false,
    available: true,
  },
  {
    id: 17,
    name: "Fanta Orange 300ml",
    category: "Drinks",
    description: "Chilled orange-flavoured Fanta, 300ml.",
    price: 70,
    priceIsEstimate: true,
    image: "images/fanta-orange-300ml.jpg",
    featured: false,
    available: true,
  },
  {
    id: 18,
    name: "Sprite 300ml",
    category: "Drinks",
    description: "Chilled lemon-lime Sprite, 300ml.",
    price: 70,
    priceIsEstimate: true,
    image: "images/sprite-300ml.jpg",
    featured: false,
    available: true,
  },
  {
    id: 19,
    name: "Stoney Tangawizi 300ml",
    category: "Drinks",
    description: "Chilled ginger-flavoured Stoney Tangawizi, 300ml.",
    price: 70,
    priceIsEstimate: true,
    image: "images/stoney-tangawizi-300ml.jpg",
    featured: false,
    available: true,
  },
  {
    id: 20,
    name: "Bottled Water 500ml",
    category: "Drinks",
    description: "Bottled drinking water, 500ml.",
    price: 50,
    priceIsEstimate: true,
    image: "images/bottled-water-500ml.jpg",
    featured: false,
    available: true,
  },
];

if (typeof module !== "undefined" && module.exports) {
  module.exports = products;
} else {
  globalThis.FBI_PRODUCTS = products;
}
})();